# Generated by Django 2.2.4 on 2019-08-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190826_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='rx',
            field=models.OneToOneField(help_text='Aquele que Escuta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RX', to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tx',
            field=models.OneToOneField(help_text='Aquele que Fala', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TX', to='core.Usuario'),
        ),
    ]
