# Generated by Django 2.2.4 on 2019-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190826_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='socketMessageEvent',
            field=models.CharField(help_text='Mensagem do Socket', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(help_text='Nome da Sala', max_length=500),
        ),
    ]
